server.port=${SERVER_PORT:8080}
app.jwt.issuer=${JWT_ISSUER:http://localhost:8080}
server.forward-headers-strategy=framework
#spring.datasource.url=jdbc:postgresql://database-1.cdy6a006w97h.eu-north-1.rds.amazonaws.com:5432/postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Pussmun_12
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
app.jwt.key-id=${JWT_KEY_ID:jwt-key-1}
app.jwt.public-key=${JWT_PUBLIC_KEY:}
app.jwt.private-key=${JWT_PRIVATE_KEY:}
