# Prod-profil - direktanslutning till AWS RDS från EC2
spring.datasource.url=${DB_URL:jdbc:postgresql://database-1.cdy6a006w97h.eu-north-1.rds.amazonaws.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
